/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-09 18:22:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addcontact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/displayformerrors.jsp", Long.valueOf(1622858251506L));
    _jspx_dependants.put("/header.html", Long.valueOf(1622858251641L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1622858251548L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>AddressBook</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#ffffee\">\r\n");
      out.write("<h1><center>AddressBook</center></h1>\r\n");
      out.write("<p align=\"center\">\r\n");
      out.write("<a href=\"/mysite/addcontact.jsp\">Add</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/deletecontact.jsp\">Delete</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/modifycontact.jsp\">Modify</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/viewcontact.jsp\">View</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/viewbygroup.jsp\">View by Group</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/servlet/viewall\">View All</a>&#160;&#183;&#160;\r\n");
      out.write("<a href=\"/mysite/quit.jsp\">Quit</a></p>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Add Contact</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffee\" leftmargin=\"10px\" rightmargin=\"10px\">\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<!-- errors display -->\r\n");
 
String formErrors = (String) request.getSession().getAttribute("Errors");

      out.write(" \r\n");
      out.write("\r\n");
if (formErrors != null && !formErrors.equals("")){
      out.write("\r\n");
      out.write("<h3><font color=\"red\" face=\"Arial, Helvetica, sans-serif\" size=\"3\">Please correct \r\n");
      out.write("the following errors and try again:</font></h3>\r\n");
      out.write("<ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<font size=\"2\" color=\"black\" face=\"Arial, Helvetica, sans-serif\">\r\n");
      out.write("\t");
      out.print(request.getSession().getAttribute("Errors") );
      out.write("</font>\r\n");
      out.write("</ul>\r\n");
 request.getSession().removeAttribute("Errors"); 
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("<!-- end errors display -->");
      out.write("\r\n");
      out.write("<h2>Add contact</h2>\r\n");
      out.write("</center>\r\n");
      out.write("<!--Body: add contact information-->\r\n");
      out.write("<center>\r\n");
      out.write("<form method=\"post\" action=\"/mysite/servlet/addemailaddress\">\r\n");
      out.write("\t<table  cellpadding=\"0\" cellspacing=\"0\" width=\"50%\"\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">E-mail</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"emailid\" maxlength=\"50\" value=\"");
      out.print( request.getParameter("emailid") );
      out.write("\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">First name</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"fname\" maxlength=\"30\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">Middle name</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"mname\" maxlength=\"10\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">Last name</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"lname\" maxlegth=\"30\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">Home Phone</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"hphone\" maxlength=\"12\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">Work Phone</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"wphone\" maxlength=\"12\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">Mobile Phone</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"mphone\" maxlength=\"12\" value=\"\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<td bgcolor=\"#FAFAF9\" style=\"padding-left: 10px;\">\r\n");
      out.write("\t\t<lable for=\"group\">Group</lable>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\t<td><select name=\"group\" id=\"group\">\r\n");
      out.write("\t\t\t<option value=7>Friends</option>\r\n");
      out.write("\t\t\t<option value=8>Personal</option>\r\n");
      out.write("\t\t\t<option value=9>Relatives</option>\r\n");
      out.write("\t\t\t</select> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"right\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table  width=\"50%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" name=\"save\" value=\"Save\"/></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"201\"><input type=\"reset\" name=\"clear\" value=\"Clear\" />&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
